### ISSUE TITLE
Removing `openbci` from npm registry

### ISSUE THREAD

**Issue by andrewjaykeller** [heavyk/affinaty#1]
Hey Kenny,

I wanted to inquire with you about unpublishing your npm module called `openbci` found [here](https://www.npmjs.com/package/openbci).

I could not find your email on the web (good job) so this was the only way i could figure out how to contact you. 

I make a node module for the [OpenBCI](http://www.openbci.com) and would like to prevent people from downloading an un-working repo. Thanks!

**Comment by heavyk** [comment]
umm, wow this is news to me... I didn't know I had published it in the first place, or even what my npm account is... lol

sure, I'll unpublish it if I can, obviously

I'll investigate and get back to you shortly with results

**Comment by andrewjaykeller** [comment]
@heavyk thanks!!

**Comment by heavyk** [comment]
ok, I reset my password and ran `npm adduser heavyk`
after it said: `Logged in as heavyk on https://registry.npmjs.org/.`
now, I try to unpublish:

```
npm unpublish openbci --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "unpublish" "openbci" "--force"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/openbci/-rev/3-de67a18b2ee84619b9b55dbd48eaf262
```

**Comment by heavyk** [comment]
so like, uhhh what do I do, do you know?

**Comment by heavyk** [comment]
ok, so I've tried different combinations of the command and all are giving me the 400 delete error. I don't really know what I can do at this point. any suggestions??

btw, this is, to my recollection, the first time I've used npm. I think that package got published one very drunk night in berlin a very long time ago. we were working on the headset, and that was code that was partially working... I guess one "good idea" lead to another and a module was published... lol

**Comment by andrewjaykeller** [comment]
@heavyk haha you have us all cracking up in NYC 👍  

It looks like you simply have to send an email to support@npmjs.com and ask them to remove it. 

They (NPM) recently changed their policy because some developer got pissed, unpublished his account, and broke the entire npm eco system because so many packages were dependent on it.

Pretty funny check out this blog post about it
 http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

**Comment by heavyk** [comment]
lol... yeah, hmmm that is sort of a bad thing was bound to happen with unpublish. I would guess that packages should be immutable and based on a hash... wow, what an ordeal. lol

I'll email them now :)

**Comment by heavyk** [comment]
sent the email and got an automated zendesk response. their hours are until 6pm pst though... I'm not sure what time that is (it's 23:00 here). I imagine this'll be sorted within the following 24 hours, so rest easy :)

cheers

**Comment by andrewjaykeller** [comment]
@heavyk thank you so much man! Appreciate it!

**Comment by andrewjaykeller** [comment]
I think you have done all you can so let's close this issue :)

**Comment by heavyk** [comment]
btw, I just checked out your website... your headset looks pretty freakin cool man.. the specs are really quite impressive too!! the berlin headset we were using was 2ch 10 bit resolution @ (I think) 2khz or something...so essentially garbage in comparison

I'm gonna be sending you guys an order soon as I organize the cash (so maybe a few months) I would need it pre-printed though as I don't have access to a 3d printer here (I'm in madrid currently). would that be possible? I guess I'll send you an email when that time comes near... the board looks super awesome 👍 👍 👍

**Comment by andrewjaykeller** [comment]
You should! It's a really great tool that is enabling quality innovation around the world. We have been working crazy hard to overhaul the firmware and create an environment that is accessible for the novice user but powerful and dynamic for the power user (researcher). Fully open source and hackable. It's great.

**Comment by heavyk** [comment]
well, it interests me greatly... I'll be emailing you within a month or so...

and, reading my email, it appears that npm has everything under control :) so, cheers! I hope everything goes well for you guys. best of luck!
